Add returnCompleteBalances
ka2n/go-poloniex pull request #1
Opened 2017-06-20 13:15 UTC by gabu

Poloniex Trading API `returnCompleteBalances` returns

```json
{"LTC":{"available":"5.015","onOrders":"1.0025","btcValue":"0.078"},"NXT:{...} ... }
```

but `GetCompleteBalances` method returns below structs.

```go
type CompleteBalances []Balance

type Balance struct {
	Symbol    string
	Available string
	OnOrders  string
	BtcValue  string
}
```

How is this?

2017-06-20 13:15 UTC, ka2n commented on private-api.go
> +func (c *Client) GetCompleteBalances(ctx context.Context) (CompleteBalances, error) {
__[golint]__
* [golint] exported method Client.GetCompleteBalances should have comment or be unexported

<!-- Comment by [SideCI](https://sideci.com) -->

2017-06-20 13:15 UTC, ka2n commented on private-api.go
> +type CompleteBalances []Balance
__[golint]__
* [golint] exported type CompleteBalances should have comment or be unexported

<!-- Comment by [SideCI](https://sideci.com) -->

2017-06-20 13:15 UTC, ka2n commented on private-api.go
> +type Balance struct {
__[golint]__
* [golint] exported type Balance should have comment or be unexported

<!-- Comment by [SideCI](https://sideci.com) -->

2017-06-20 13:42 UTC, ka2n commented
@gabu How about `type CompleteBalances map[string]Balance`?

It's easy user to retrieve a balance of specific currency.

2017-06-20 13:52 UTC, ka2n requested changes

2017-06-20 13:52 UTC, ka2n commented on private-api.go
> +	var ret map[string]interface{}
declare response struct that implements `json.Unmarshaler` and use it

2017-06-20 13:52 UTC, ka2n commented on private-api.go
> +		i, err := strconv.ParseFloat(balance["btcValue"].(string), 64)
What is the use case of "btcValue" contains non float?

2017-06-20 14:06 UTC, gabu commented on private-api.go
> +	var ret map[string]interface{}
I wanna use Unmarshaler but Poloniex returns two pattern...

1. error

```
{"error":"<error message>"}
```

2. success

```
{"LTC":{"available":"5.015","onOrders":"1.0025","btcValue":"0.078"},"NXT:{...} ... }
```

How declare struct in this case?

2017-06-20 14:10 UTC, gabu commented on private-api.go
> +		i, err := strconv.ParseFloat(balance["btcValue"].(string), 64)
"btcValue" is string in JSON.

I tried  `balance["btcValue"].(float64)` then happened a below panic.

```
panic: interface conversion: interface {} is string, not float64
```

2017-06-20 14:13 UTC, ka2n commented on private-api.go
> +	var ret map[string]interface{}
```go
type Resp struct {
  Balances map[string]Balance
  Error string `json:"error"`
}

func (*r Resp) UnmarshalJSON(data byte[]) error {
  var raw interface{}
  err := json.Unmarshal(data, &raw)
  ...
}
```

2017-06-20 14:18 UTC, ka2n commented on private-api.go
> +		i, err := strconv.ParseFloat(balance["btcValue"].(string), 64)
Got it, but is it necessary? `Balance.BtcValue` is also string, it can be decoded into directly.

2017-06-20 15:32 UTC, gabu commented on private-api.go
> +		i, err := strconv.ParseFloat(balance["btcValue"].(string), 64)
I wanna reject not own pairs but this is a meddler, will be delete.

2017-06-20 15:33 UTC, ka2n commented on private-api.go
> +type CompleteBalances map[string]Balance
__[golint]__
* [golint] exported type CompleteBalances should have comment or be unexported

<!-- Comment by [SideCI](https://sideci.com) -->

2017-06-20 15:33 UTC, ka2n commented on private-api.go
> +type Balance struct {
__[golint]__
* [golint] exported type Balance should have comment or be unexported

<!-- Comment by [SideCI](https://sideci.com) -->

2017-06-20 15:36 UTC, gabu commented
Please review again 🙇

2017-06-20 17:09 UTC, ka2n commented on private-api.go
> +func (c *Client) GetCompleteBalances(ctx context.Context) (CompleteBalances, error) {
Please add comment to the function above :art:

2017-06-21 07:27 UTC, gabu commented on private-api.go
> +func (c *Client) GetCompleteBalances(ctx context.Context) (CompleteBalances, error) {
I commented to added methods and types.

2017-06-21 08:24 UTC, ka2n commented on private-api.go
> +func (c *Client) GetCompleteBalances(ctx context.Context) (CompleteBalances, error) {
thank you!

2017-06-21 08:25 UTC, ka2n approved these changes

2017-06-21 08:25 UTC, merged

2017-06-21 13:30 UTC, gabu commented
Thanks mate 💪